### ISSUE TITLE
Posting  bid form does not add existing issue to Bid.issue

### ISSUE THREAD

**Issue by jdungan** [codesy/codesy#257]
Steps to recreate:
1) Create a new bid with User 1 on a new url.  The issue is properly created.
2) Now create a bid with User 2 on the same url.  Bid.issue is None.

There is a test for this (BidTests.test_save_assigns_issue_for_existing_url) but it only test to see that a new issue is not created.  Testing Bid.issue in the test will show None.

Solving this will mean updating the test as well.

**Comment by jdungan** [comment]
Run the steps above and the second Bid does not get an issue.

**Comment by jdungan** [comment]
Hmm.  Using the swagger UI works so something must be wrong with the widget form.

**Comment by jdungan** [comment]
It's not the widget form.  The notify_matching_askers is failing so the create_issue_for_bid signal does not execute.  Here the server error:

Internal Server Error: /bids/86/
Traceback (most recent call last):
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/rest_framework/mixins.py", line 70, in update
    self.perform_update(serializer)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/rest_framework/mixins.py", line 74, in perform_update
    serializer.save()
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/rest_framework/serializers.py", line 186, in save
    self.instance = self.update(self.instance, validated_data)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/rest_framework/serializers.py", line 880, in update
    instance.save()
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/models/base.py", line 737, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/owner/projects/codesy/codesy/auctions/models.py", line 70, in notify_matching_askers
    [bid.user.email]
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/mailer/__init__.py", line 54, in send_mail
    priority=priority).save()
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/models/base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/models/base.py", line 812, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/models/base.py", line 851, in _do_insert
    using=using, raw=raw)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: table mailer_message has no column named message_data
[13/Mar/2016 00:08:27] "PUT /bids/86/ HTTP/1.1" 500 19675

**Comment by groovecoder** [comment]
Try to run `python manage.py migrate` - it should create the `mailer_message` table for you.

**Comment by groovecoder** [comment]
Oh, and the reason the test passes is that the test suite destroys and re-creates the database every time it runs, so it forces the `mailer_message` table to create.

**Comment by jdungan** [comment]
Just made a migration applied it.  Same error

**Comment by groovecoder** [comment]
What migration? Was it in the mailer app? Can you paste the output?

**Comment by jdungan** [comment]
For some reason, when I tried to migrate, on my local master, I got this:

  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

So I ran makemigrations, which created a migration, then I ran that. 

When I still got the error, I blew away the whole local branch and then attached to codesy/master.

**Comment by jdungan** [comment]
Go here:
https://127.0.0.1:8443/admin/mailer/messagelog/

I see this:

Environment:


Request Method: GET
Request URL: https://127.0.0.1:8443/admin/mailer/messagelog/

Django Version: 1.9.3
Python Version: 2.7.5
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.github',
 'corsheaders',
 'mailer',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_framework_swagger',
 'codesy.base',
 'api',
 'auctions')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')



Traceback:

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/contrib/admin/options.py" in wrapper
  541.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/contrib/admin/sites.py" in inner
  244.             return view(request, *args, **kwargs)

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/contrib/admin/options.py" in changelist_view
  1577.             selection_note=_('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/models/query.py" in __len__
  240.         self._fetch_all()

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/models/query.py" in _fetch_all
  1074.             self._result_cache = list(self.iterator())

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/models/query.py" in __iter__
  52.         results = compiler.execute_sql()

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/models/sql/compiler.py" in execute_sql
  848.             cursor.execute(sql, params)

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  79.             return super(CursorDebugWrapper, self).execute(sql, params)

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/utils.py" in __exit__
  95.                 six.reraise(dj_exc_type, dj_exc_value, traceback)

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)

File "/Users/owner/projects/python_envs/codesy/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py" in execute
  323.         return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /admin/mailer/messagelog/
Exception Value: no such column: mailer_messagelog.message_data

**Comment by groovecoder** [comment]
The `mailer` app messed up their migration history at some point. :cry: So you may have to do this:
```
$ psql codesy
codesy=# drop table mailer_dontsendentry, mailer_message, mailer_messagelog;
DROP TABLE
codesy=# delete from django_migrations where app = 'mailer';
DELETE 2
```
Then go back and `python manage.py migrate` again to properly re-create the `mailer_*` tables that match the real migrations.
