### ISSUE TITLE
django.db.utils:ProgrammingError  /auctions.views:BidStatusView.post

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#378]
```

Traceback (most recent call last):
File "/app/.heroku/python/bin/gunicorn", line 11, in <module>
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 180, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 482, in manage_workers
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 548, in spawn_workers
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 119, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 66, in run_for_one
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 30, in accept
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/app/.heroku/python/lib/python2.7/site-packages/dj_static.py", line 83, in __call__
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/mixins.py", line 116, in dispatch
File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 872, in wrapper
File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
File "/app/auctions/views.py", line 77, in post
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 700, in save
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 737, in save_base
File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 192, in send
File "/app/auctions/models.py", line 155, in notify_matching_askers
File "/app/.heroku/python/lib/python2.7/site-packages/mailer/__init__.py", line 54, in send_mail
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 700, in save
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 728, in save_base
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 812, in _save_table
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 851, in _do_insert
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/hooks/database_dbapi2.py", line 22, in execute
```

**Comment by groovecoder** [comment]
I think I fixed this by DROPing and re-CREATEing the mailer_* tables. Need to test on prod.

**Comment by groovecoder** [comment]
Verified fixed.
