### ISSUE TITLE
Server Error 500 when downloading CSV from admin

### ISSUE THREAD

**Issue by aprilchomp** [codesy/codesy#626]
I keep getting Server Error (500) when trying to download a user CSV.  
Can only do one at a time successfully. 
Sad Face

**Comment by groovecoder** [comment]
Ah, I finally found out why this happens on prod but not local or stage ... looks like someone has a non-ascii character in their `first_name` and/or `last_name` ...

```

Error message

exceptions:UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)
Stack trace
Traceback (most recent call last):
File "/app/.heroku/python/bin/gunicorn", line 11, in <module>
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 180, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 482, in manage_workers
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 548, in spawn_workers
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 119, in run
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 66, in run_for_one
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 30, in accept
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/app/.heroku/python/lib/python2.7/site-packages/dj_static.py", line 83, in __call__
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/options.py", line 551, in wrapper
File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
File "/app/.heroku/python/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1568, in changelist_view
File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1286, in response_action
File "/app/codesy/base/admin.py", line 23, in download_user_csv
```

Will need to handle non-ascii characters before writing the records out to CSV.
